apiVersion: v1
kind: Service
metadata:
  name: podcast-server
  namespace: default
  labels:
    app: podcast-server
spec:
  ports:
  - name: 3000tcp01
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: podcast-server
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podcast-server
  labels:
    app: podcast-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podcast-server
  template:
    metadata:
      labels:
        app: podcast-server
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: podcast-server
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        env:
          - name: serverName
            value: "https://podcast.f7i.de"
          - name: port
            value: "3000"
        ports:
        - containerPort: 3000
          name: podcast-server